### ISSUE TITLE
App crashes when call is ended

### ISSUE THREAD

**Issue by malikhijazi** [callstack/react-native-opentok#12]
App crashes when call is ended by subscriber. Fails at return UIApplicationMain(argc, argv, nil, NSStringFromClass([AppDelegate class]) in main. The error is EXC_BAD_ACCESS code=EXC_I386_GPFLT. This issue appears only when a client enters a chat, leaves the chat, enters again, and then leaves once more.

**Comment by ainurb** [comment]
@malikhijazi  hi, my app crashes when client enters a chat for the first time, have you met this error https://github.com/callstack-io/react-native-opentok/issues/11 ?

**Comment by 3MF** [comment]
@malikhijazi The code found in the `streamDestroyed` method of `RCTOpenTokSubscriberView.m` seems to be the culprit here. From my understanding, `subscriberDidDisconnectFromStream` is called before `streamDestroyed`, and thus `_onSubscribeStop(@{})` and `[self cleanupSubscriber]` are called ahead of `streamDestroyed`'s invocation of `_onSubscribeStop(@{})`. A quick fix is to simply comment out the offending code in `streamDestroyed()`:

```objective-c
// RCTOpenTokSubscriberView.m

- (void)session:(OTSession *)session streamDestroyed:(OTStream *)stream
{
  // _onSubscribeStop(@{});
  NSLog(@"Subscriber stream destroyed");
}
```

**Comment by mike866** [comment]
Hey!

Thanks for your feedback. We rewrote the library completely, which results in API changes and many bug fixes. If the issue still persists on the latest version, please re-open it. 

Thanks!
