### ISSUE TITLE
npm install react-native-opentok installs only package.json file and nothing more

### ISSUE THREAD

**Issue by MieszkoGulinski** [callstack/react-native-opentok#25]
After running
`npm install react-native-opentok`
in
`(path to RN project)/node_modules/react-native-opentok` we have only some `package.json` file with untypical/undocumented keys. No other files are installed. Also, both the installed file and npm website show version 1.0.14, while in the GitHub repository package.json shows version 0.0.1.

My configuration: npm 4.6.1, Node 7.10.0, Mac.

The workaround is to change/dependency in our app's `package.json` to
`"react-native-opentok": "git+ssh://git@github.com:callstack-io/react-native-opentok.git"`

**Comment by chuckhacker** [comment]
We're also experiencing this issue

**Comment by morksinaanab** [comment]
The reason is probably that this package is not registered as a node package. So when you do `npm install react-native-opentok` you are installing a completely different node module.

Whereas there is another node package 'react-native-opentok' that you then are installing https://www.npmjs.com/package/react-native-opentok <-- that's a different module.

**Comment by mike866** [comment]
Hey!

Thanks for your feedback. We rewrote the library completely, which results in API changes and many bug fixes. If the issue still persists on the latest version, please re-open it. 

Thanks!
